tmux new -d -s t0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=0 --gpu=0 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=1 --gpu=0 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=2 --gpu=0 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=3 --gpu=0 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t4 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=4 --gpu=1 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t5 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=5 --gpu=1 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t6 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=6 --gpu=1 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t7 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=7 --gpu=1 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t8 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=8 --gpu=2 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t9 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=9 --gpu=2 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t10 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=10 --gpu=2 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t11 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=11 --gpu=2 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t12 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=12 --gpu=3 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t13 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=13 --gpu=3 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t14 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=14 --gpu=3 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t15 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=15 --gpu=3 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'

tmux new -d -s t16 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=16 --gpu=4 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t17 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=17 --gpu=4 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t18 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=18 --gpu=4 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t19 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=19 --gpu=4 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t20 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=20 --gpu=5 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t21 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=21 --gpu=5 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t22 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=22 --gpu=5 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t23 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=23 --gpu=5 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t24 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=24 --gpu=6 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t25 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=25 --gpu=6 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t26 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=26 --gpu=6 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t27 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=27 --gpu=6 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t28 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=28 --gpu=7 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t29 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=29 --gpu=7 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t30 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=30 --gpu=7 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'
tmux new -d -s t31 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=31 --gpu=7 --gpu_usage=0.22 --load_epoch=0 --n_epochs=30'


remove=1183514
for i in  "$remove"*;do mv "$i" "${i#"$remove"}";done